// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo_IwX1HEAepNZOfPxd_HGNsXNiXnOoqg',
    appId: '1:412623487000:web:caec0f062b23642009436d',
    messagingSenderId: '412623487000',
    projectId: 'collabquest-3e364',
    authDomain: 'collabquest-3e364.firebaseapp.com',
    storageBucket: 'collabquest-3e364.firebasestorage.app',
    measurementId: 'G-KH460847EC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrypALAkCtwbue2vlB_7oWDLL1oQk92y0',
    appId: '1:412623487000:android:3a45e1f0323eba6e09436d',
    messagingSenderId: '412623487000',
    projectId: 'collabquest-3e364',
    storageBucket: 'collabquest-3e364.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpXi6mVtOpJrVA8iQmnGyzv_HgKUWqbmE',
    appId: '1:412623487000:ios:2b192950d138e5f209436d',
    messagingSenderId: '412623487000',
    projectId: 'collabquest-3e364',
    storageBucket: 'collabquest-3e364.firebasestorage.app',
    iosBundleId: 'com.hakimi.collabquest.collabQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpXi6mVtOpJrVA8iQmnGyzv_HgKUWqbmE',
    appId: '1:412623487000:ios:2b192950d138e5f209436d',
    messagingSenderId: '412623487000',
    projectId: 'collabquest-3e364',
    storageBucket: 'collabquest-3e364.firebasestorage.app',
    iosBundleId: 'com.hakimi.collabquest.collabQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo_IwX1HEAepNZOfPxd_HGNsXNiXnOoqg',
    appId: '1:412623487000:web:5b48deb5b3f5d23909436d',
    messagingSenderId: '412623487000',
    projectId: 'collabquest-3e364',
    authDomain: 'collabquest-3e364.firebaseapp.com',
    storageBucket: 'collabquest-3e364.firebasestorage.app',
    measurementId: 'G-TTTQSWTWS8',
  );
}
